import { FaCat, FaDog, FaHandLizard } from "react-icons/fa";
import { GiRabbit } from "react-icons/gi";
import { ENotificationsTypes } from "./components/Notification";
import { IRealUser, IUser } from "./interfaces/user.interface";
import { IconType } from "react-icons";
import { IFlat, IRealFlat } from "./interfaces/flat.interface";
import { IArticle } from "./interfaces/article.interface";

export type TAnimals = "cat" | "dog" | "lizard" | "rabbit";

export type THabits = "smoking" | "sport" | "night owl" | "early bird";

export const bigScreenSize = 850;

export const mobileBottomMenuIcons: [string, string][] = [
  ["/", "home"],
  ["/flats", "building"],
  ["/neighbors", "human"],
  ["/favourites", "favourites"],
  ["/chat", "message"],
];

export const storyList = [
  {
    url: "https://i.pinimg.com/originals/29/96/cb/2996cb6f86eebfedfc0750e783eb7f31.jpg",
  },
  {
    url: "https://i.pinimg.com/736x/7c/ef/11/7cef116d9b842f010a4d77ad21e9fcc5.jpg",
  },
  {
    url: "https://i.pinimg.com/originals/29/96/cb/2996cb6f86eebfedfc0750e783eb7f31.jpg",
  },
  {
    url: "https://i.pinimg.com/736x/7c/ef/11/7cef116d9b842f010a4d77ad21e9fcc5.jpg",
  },
  {
    url: "https://i.pinimg.com/originals/29/96/cb/2996cb6f86eebfedfc0750e783eb7f31.jpg",
  },
  {
    url: "https://i.pinimg.com/736x/7c/ef/11/7cef116d9b842f010a4d77ad21e9fcc5.jpg",
  },
  {
    url: "https://i.pinimg.com/originals/29/96/cb/2996cb6f86eebfedfc0750e783eb7f31.jpg",
  },
  {
    url: "https://i.pinimg.com/736x/7c/ef/11/7cef116d9b842f010a4d77ad21e9fcc5.jpg",
  },
];

export const LinkCards: [string, string, string][] = [
  ["housing", "Поиск жилья", "/flats"],
  ["humans", "Поиск людей", "/neighbors"],
  ["about", "Журнал", "/articles"],
  ["addHousing", "Добавить жилье", "/add-apartment/1"],
];

export const FlatList: IRealFlat[] = [
  {
    address: "Москва",
    type: "UK",
    type_extra: "",
    i_am_owner: true,
    count_days_from: 10,
    count_days_to: 110,
    cost: 11000,
    is_have_bail: true,
    is_have_fines: true,
    cost_utilities: 1100,
    count_neighbors: 0,
    count_rooms: 3,
    floor: 4,
    building_floor: 9,
    repair_type: "UK",
    repair_type_extra: "",
    building_type: "UK",
    building_type_extra: "",
    sound_insulation_type: "UK",
    sound_insulation_type_extra: "",
    accessibility_type: "UK",
    accessibility_type_extra: "",
    is_sunny_side: true,
    is_have_elevator: true,
    is_have_balcony: true,
    is_have_parking_space: true,
    is_have_security: true,
    is_have_horizontal_bars: true,
    is_have_conditioner: true,
    is_have_garbage_chute: true,
    is_have_wifi: true,
    is_have_transport_close: true,
    is_possible_smoke: true,
    is_possible_animals: true,
    is_have_washing_machine: true,
    is_have_dryer: true,
    is_have_iron: true,
    is_have_dishwasher: true,
    is_have_hair_dryer: true,
    is_have_tv: true,
    is_have_guest_table: true,
    is_have_guest_cabinet: true,
    photos_ids: [
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
    ],
    description: "Здесь представлено описание предложения от автора",
    id: 0,
    creator_id: 0,
    changed: "2024-09-11T23:22:18.039Z",
    created: "2024-09-11T23:22:18.039Z",
    is_active: true,
    viewes: 0,
    is_favorite: true,
  },
  {
    address: "Москва",
    type: "UK",
    type_extra: "",
    i_am_owner: true,
    count_days_from: 10,
    count_days_to: 110,
    cost: 11000,
    is_have_bail: true,
    is_have_fines: true,
    cost_utilities: 1100,
    count_neighbors: 0,
    count_rooms: 3,
    floor: 4,
    building_floor: 9,
    repair_type: "UK",
    repair_type_extra: "",
    building_type: "UK",
    building_type_extra: "",
    sound_insulation_type: "UK",
    sound_insulation_type_extra: "",
    accessibility_type: "UK",
    accessibility_type_extra: "",
    is_sunny_side: true,
    is_have_elevator: true,
    is_have_balcony: true,
    is_have_parking_space: true,
    is_have_security: true,
    is_have_horizontal_bars: true,
    is_have_conditioner: true,
    is_have_garbage_chute: true,
    is_have_wifi: true,
    is_have_transport_close: true,
    is_possible_smoke: true,
    is_possible_animals: true,
    is_have_washing_machine: true,
    is_have_dryer: true,
    is_have_iron: true,
    is_have_dishwasher: true,
    is_have_hair_dryer: true,
    is_have_tv: true,
    is_have_guest_table: true,
    is_have_guest_cabinet: true,
    photos_ids: [
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
    ],
    description: "Здесь представлено описание предложения от автора",
    id: 0,
    creator_id: 0,
    changed: "2024-09-11T23:22:18.039Z",
    created: "2024-09-11T23:22:18.039Z",
    is_active: true,
    viewes: 0,
    is_favorite: true,
  },
  {
    address: "Москва",
    type: "UK",
    type_extra: "",
    i_am_owner: true,
    count_days_from: 10,
    count_days_to: 110,
    cost: 11000,
    is_have_bail: true,
    is_have_fines: true,
    cost_utilities: 1100,
    count_neighbors: 0,
    count_rooms: 3,
    floor: 4,
    building_floor: 9,
    repair_type: "UK",
    repair_type_extra: "",
    building_type: "UK",
    building_type_extra: "",
    sound_insulation_type: "UK",
    sound_insulation_type_extra: "",
    accessibility_type: "UK",
    accessibility_type_extra: "",
    is_sunny_side: true,
    is_have_elevator: true,
    is_have_balcony: true,
    is_have_parking_space: true,
    is_have_security: true,
    is_have_horizontal_bars: true,
    is_have_conditioner: true,
    is_have_garbage_chute: true,
    is_have_wifi: true,
    is_have_transport_close: true,
    is_possible_smoke: true,
    is_possible_animals: true,
    is_have_washing_machine: true,
    is_have_dryer: true,
    is_have_iron: true,
    is_have_dishwasher: true,
    is_have_hair_dryer: true,
    is_have_tv: true,
    is_have_guest_table: true,
    is_have_guest_cabinet: true,
    photos_ids: [
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
    ],
    description: "Здесь представлено описание предложения от автора",
    id: 0,
    creator_id: 0,
    changed: "2024-09-11T23:22:18.039Z",
    created: "2024-09-11T23:22:18.039Z",
    is_active: true,
    viewes: 0,
    is_favorite: true,
  },
  {
    address: "Москва",
    type: "UK",
    type_extra: "",
    i_am_owner: true,
    count_days_from: 10,
    count_days_to: 110,
    cost: 11000,
    is_have_bail: true,
    is_have_fines: true,
    cost_utilities: 1100,
    count_neighbors: 0,
    count_rooms: 3,
    floor: 4,
    building_floor: 9,
    repair_type: "UK",
    repair_type_extra: "",
    building_type: "UK",
    building_type_extra: "",
    sound_insulation_type: "UK",
    sound_insulation_type_extra: "",
    accessibility_type: "UK",
    accessibility_type_extra: "",
    is_sunny_side: true,
    is_have_elevator: true,
    is_have_balcony: true,
    is_have_parking_space: true,
    is_have_security: true,
    is_have_horizontal_bars: true,
    is_have_conditioner: true,
    is_have_garbage_chute: true,
    is_have_wifi: true,
    is_have_transport_close: true,
    is_possible_smoke: true,
    is_possible_animals: true,
    is_have_washing_machine: true,
    is_have_dryer: true,
    is_have_iron: true,
    is_have_dishwasher: true,
    is_have_hair_dryer: true,
    is_have_tv: true,
    is_have_guest_table: true,
    is_have_guest_cabinet: true,
    photos_ids: [
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
      "https://cdn1.ozone.ru/s3/multimedia-k/6447918644.jpg",
      "https://img.dmclk.ru/vitrina/owner/ce/5e/ce5ee961a36f4648864c92328a8263e0.jpg",
    ],
    description: "Здесь представлено описание предложения от автора",
    id: 0,
    creator_id: 0,
    changed: "2024-09-11T23:22:18.039Z",
    created: "2024-09-11T23:22:18.039Z",
    is_active: true,
    viewes: 0,
    is_favorite: true,
  },
];

export const usersList: IRealUser[] = [
  {
    id: 0,
    first_name: "jon1",
    date_joined: "2024-09-12T07:03:08.944Z",
    count_visits: 0,
    avatar: "https://28.img.avito.st/avatar/social/1024x1024/4062977028.jpg",
    purpose: "JB",
    occupation: "UK",
    smoking: "U",
    pets: "U",
    first_aid: "U",
    social_interaction: "U",
    home_town: "Питер",
    my_town: "Москва",
    is_favorite: true,
  },
  {
    id: 1,
    first_name: "jon2",
    date_joined: "2024-09-12T07:03:08.944Z",
    count_visits: 0,
    avatar: "",
    purpose: "JB",
    occupation: "UK",
    smoking: "U",
    pets: "U",
    first_aid: "U",
    social_interaction: "U",
    home_town: "Питер",
    my_town: "Москва",
    is_favorite: true,
  },
  {
    id: 2,
    first_name: "jon3",
    date_joined: "2024-09-12T07:03:08.944Z",
    count_visits: 0,
    avatar: "",
    purpose: "JB",
    occupation: "UK",
    smoking: "U",
    pets: "U",
    first_aid: "U",
    social_interaction: "U",
    home_town: "Питер",
    my_town: "Москва",
    is_favorite: true,
  },
  {
    id: 3,
    first_name: "jon4",
    date_joined: "2024-09-12T07:03:08.944Z",
    count_visits: 0,
    avatar: "",
    purpose: "JB",
    occupation: "UK",
    smoking: "U",
    pets: "U",
    first_aid: "U",
    social_interaction: "U",
    home_town: "Питер",
    my_town: "Москва",
    is_favorite: true,
  },
  {
    id: 4,
    first_name: "jon5",
    date_joined: "2024-09-12T07:03:08.944Z",
    count_visits: 0,
    avatar: "",
    purpose: "JB",
    occupation: "UK",
    smoking: "U",
    pets: "U",
    first_aid: "U",
    social_interaction: "U",
    home_town: "Питер",
    my_town: "Москва",
    is_favorite: true,
  },
];

export const LinkCardsProfile: [string, string, string][] = [
  ["animals", "Животные", "/animals"],
  ["medic", "Умею и готов оказать первую помощь", "/medic"],
  ["lesson", "Род занятий", "/occupation"],
  ["habits", "Привычки", "/habits"],
];

export const users: Array<IUser> = [
  {
    id: 1,
    name: "Вася Пупкин",
    username: "vasa",
    age: 17,
    animals: ["cat"],
    favourites: {
      flats: [],
      users: [],
      articles: [],
    },
    habits: ["smoking", "night owl"],
    parameters: [
      {
        name: "Цель",
        value: "Ищу жилье",
        image: "purpose",
      },
      {
        name: "Статус",
        value: "Готов общаться просто так",
        image: "pencil",
      },
    ],
    notifications: [
      [
        ENotificationsTypes.new,
        "Важное уведомление от администрации или приложения",
        false,
      ],
      [ENotificationsTypes.read, "Важное уведомление от рассылки", false],
      [ENotificationsTypes.new, "Важное уведомление от пользователей", false],
    ],
    city: "Москва",
    contact: {
      telegram: "@vasa",
      vk: "@vasa",
      phone: "+7 (900) 123-45-67",
      mail: "ceo@nordwibe.com",
    },
  },
  {
    id: 2,
    name: "Никита Какой-то",
    username: "kak",
    age: 20,
    animals: ["dog", "lizard", "rabbit"],
    favourites: {
      flats: [],
      users: [],
      articles: [],
    },
    habits: ["smoking", "night owl"],
    parameters: [
      {
        name: "Цель",
        value: "Ищу соседа",
        image: "purpose",
      },
      {
        name: "Статус",
        value: "По делу",
        image: "pencil",
      },
    ],
    notifications: [
      [
        ENotificationsTypes.new,
        "Важное уведомление от администрации или приложения",
        false,
      ],
      [ENotificationsTypes.new, "Важное уведомление от рассылки", false],
      [ENotificationsTypes.read, "Важное уведомление от пользователей", false],
    ],
    city: "Москва",
    contact: {
      telegram: "@xyi",
      vk: "@xyi",
      phone: "+7 (900) 123-45-67",
      mail: "ceo@nordwibe.com",
    },
  },
  {
    id: 3,
    name: "Вася Пупкин2.0",
    username: "visa",
    age: 17,
    animals: ["cat"],
    favourites: {
      flats: [],
      users: [],
      articles: [],
    },
    habits: ["smoking", "night owl"],
    parameters: [
      {
        name: "Цель",
        value: "Страдать",
        image: "purpose",
      },
      {
        name: "Статус",
        value: "Писать по делу",
        image: "pencil",
      },
    ],
    notifications: [
      [
        ENotificationsTypes.new,
        "Важное уведомление от администрации или приложения",
        false,
      ],
      [ENotificationsTypes.read, "Важное уведомление от рассылки", false],
      [ENotificationsTypes.new, "Важное уведомление от пользователей", false],
    ],
    city: "Москва",
    contact: {
      telegram: "@visa",
      vk: "@visa",
      phone: "+7 (900) 123-45-67",
      mail: "ceo@nordwibe.com",
    },
  },
];

export const cities: Array<string> = [
  "Абаза",
  "Абакан",
  "Абдулино",
  "Абинск",
  "Агидель",
  "Агрыз",
  "Адыгейск",
  "Азнакаево",
  "Азов",
  "Ак",
  "Аксай",
  "Алагир",
  "Алапаевск",
  "Алатырь",
  "Алдан",
  "Алейск",
  "Александров",
  "Александровск",
  "Александровск",
  "Алексеевка",
  "Алексин",
  "Алзамай",
  "Алупка",
  "Алушта",
  "Альметьевск",
  "Амурск",
  "Анадырь",
  "Анапа",
  "Ангарск",
  "Андреаполь",
  "Анжеро",
  "Анива",
  "Апатиты",
  "Апрелевка",
  "Апшеронск",
  "Арамиль",
  "Аргун",
  "Ардатов",
  "Ардон",
  "Арзамас",
  "Аркадак",
  "Армавир",
  "Армянск",
  "Арсеньев",
  "Арск",
  "Артём",
  "Артёмовск",
  "Артёмовский",
  "Архангельск",
  "Асбест",
  "Асино",
  "Астрахань",
  "Аткарск",
  "Ахтубинск",
  "Ачинск",
  "Аша",
  "Бабаево",
  "Бабушкин",
  "Бавлы",
  "Багратионовск",
  "Байкальск",
  "Баймак",
  "Бакал",
  "Баксан",
  "Балабаново",
  "Балаково",
  "Балахна",
  "Балашиха",
  "Балашов",
  "Балей",
  "Балтийск",
  "Барабинск",
  "Барнаул",
  "Барыш",
  "Батайск",
  "Бахчисарай",
  "Бежецк",
  "Белая Калитва",
  "Белая Холуница",
  "Белгород",
  "Белебей",
  "Белёв",
  "Белинский",
  "Белово",
  "Белогорск",
  "Белогорск",
  "Белозерск",
  "Белокуриха",
  "Беломорск",
  "Белоозёрский",
  "Белорецк",
  "Белореченск",
  "Белоусово",
  "Белоярский",
  "Белый",
  "Бердск",
  "Березники",
  "Берёзовский",
  "Берёзовский",
  "Беслан",
  "Бийск",
  "Бикин",
  "Билибино",
  "Биробиджан",
  "Бирск",
  "Бирюсинск",
  "Бирюч",
  "Благовещенск",
  "Благовещенск",
  "Благодарный",
  "Бобров",
  "Богданович",
  "Богородицк",
  "Богородск",
  "Боготол",
  "Богучар",
  "Бодайбо",
  "Бокситогорск",
  "Болгар",
  "Бологое",
  "Болотное",
  "Болохово",
  "Болхов",
  "Большой Камень",
  "Бор",
  "Борзя",
  "Борисоглебск",
  "Боровичи",
  "Боровск",
  "Бородино",
  "Братск",
  "Бронницы",
  "Брянск",
  "Бугульма",
  "Бугуруслан",
  "Будённовск",
  "Бузулук",
  "Буинск",
  "Буй",
  "Буйнакск",
  "Бутурлиновка",
  "Валдай",
  "Валуйки",
  "Велиж",
  "Великие Луки",
  "Великий Новгород",
  "Великий Устюг",
  "Вельск",
  "Венёв",
  "Верещагино",
  "Верея",
  "Верхнеуральск",
  "Верхний Тагил",
  "Верхний Уфалей",
  "Верхняя Пышма",
  "Верхняя Салда",
  "Верхняя Тура",
  "Верхотурье",
  "Верхоянск",
  "Весьегонск",
  "Ветлуга",
  "Видное",
  "Вилюйск",
  "Вилючинск",
  "Вихоревка",
  "Вичуга",
  "Владивосток",
  "Владикавказ",
  "Владимир",
  "Волгоград",
  "Волгодонск",
  "Волгореченск",
  "Волжск",
  "Волжский",
  "Вологда",
  "Володарск",
  "Волоколамск",
  "Волосово",
  "Волхов",
  "Волчанск",
  "Вольск",
  "Воркута",
  "Воронеж",
  "Ворсма",
  "Воскресенск",
  "Воткинск",
  "Всеволожск",
  "Вуктыл",
  "Выборг",
  "Выкса",
  "Высоковск",
  "Высоцк",
  "Вытегра",
  "Вышний Волочёк",
  "Вяземский",
  "Вязники",
  "Вязьма",
  "Вятские Поляны",
  "Гаврилов Посад",
  "Гаврилов",
  "Гагарин",
  "Гаджиево",
  "Гай",
  "Галич",
  "Гатчина",
  "Гвардейск",
  "Гдов",
  "Геленджик",
  "Георгиевск",
  "Глазов",
  "Голицыно",
  "Горбатов",
  "Горно",
  "Горнозаводск",
  "Горняк",
  "Городец",
  "Городище",
  "Городовиковск",
  "Гороховец",
  "Горячий Ключ",
  "Грайворон",
  "Гремячинск",
  "Грозный",
  "Грязи",
  "Грязовец",
  "Губаха",
  "Губкин",
  "Губкинский",
  "Гудермес",
  "Гуково",
  "Гулькевичи",
  "Гурьевск",
  "Гурьевск",
  "Гусев",
  "Гусиноозёрск",
  "Гусь",
  "Давлеканово",
  "Дагестанские Огни",
  "Далматово",
  "Дальнегорск",
  "Дальнереченск",
  "Данилов",
  "Данков",
  "Дегтярск",
  "Дедовск",
  "Демидов",
  "Дербент",
  "Десногорск",
  "Джанкой",
  "Дзержинск",
  "Дзержинский",
  "Дивногорск",
  "Дигора",
  "Димитровград",
  "Дмитриев",
  "Дмитров",
  "Дмитровск",
  "Дно",
  "Добрянка",
  "Долгопрудный",
  "Долинск",
  "Домодедово",
  "Донецк",
  "Донской",
  "Дорогобуж",
  "Дрезна",
  "Дубна",
  "Дубовка",
  "Дудинка",
  "Духовщина",
  "Дюртюли",
  "Дятьково",
  "Евпатория",
  "Егорьевск",
  "Ейск",
  "Екатеринбург",
  "Елабуга",
  "Елец",
  "Елизово",
  "Ельня",
  "Еманжелинск",
  "Емва",
  "Енисейск",
  "Ермолино",
  "Ершов",
  "Ессентуки",
  "Ефремов",
  "Железноводск",
  "Железногорск",
  "Железногорск",
  "Железногорск",
  "Жердевка",
  "Жигулёвск",
  "Жиздра",
  "Жирновск",
  "Жуков",
  "Жуковка",
  "Жуковский",
  "Завитинск",
  "Заводоуковск",
  "Заволжск",
  "Заволжье",
  "Задонск",
  "Заинск",
  "Закаменск",
  "Заозёрный",
  "Заозёрск",
  "Западная Двина",
  "Заполярный",
  "Зарайск",
  "Заречный",
  "Заречный",
  "Заринск",
  "Звенигово",
  "Звенигород",
  "Зверево",
  "Зеленогорск",
  "Зеленоградск",
  "Зеленодольск",
  "Зеленокумск",
  "Зерноград",
  "Зея",
  "Зима",
  "Златоуст",
  "Злынка",
  "Змеиногорск",
  "Знаменск",
  "Зубцов",
  "Зуевка",
  "Ивангород",
  "Иваново",
  "Ивантеевка",
  "Ивдель",
  "Игарка",
  "Ижевск",
  "Избербаш",
  "Изобильный",
  "Иланский",
  "Инза",
  "Иннополис",
  "Инсар",
  "Инта",
  "Ипатово",
  "Ирбит",
  "Иркутск",
  "Исилькуль",
  "Искитим",
  "Истра",
  "Ишим",
  "Ишимбай",
  "Йошкар",
  "Кадников",
  "Казань",
  "Калач",
  "Калач",
  "Калачинск",
  "Калининград",
  "Калининск",
  "Калтан",
  "Калуга",
  "Калязин",
  "Камбарка",
  "Каменка",
  "Каменногорск",
  "Каменск",
  "Каменск",
  "Камень",
  "Камешково",
  "Камызяк",
  "Камышин",
  "Камышлов",
  "Канаш",
  "Кандалакша",
  "Канск",
  "Карабаново",
  "Карабаш",
  "Карабулак",
  "Карасук",
  "Карачаевск",
  "Карачев",
  "Каргат",
  "Каргополь",
  "Карпинск",
  "Карталы",
  "Касимов",
  "Касли",
  "Каспийск",
  "Катав",
  "Катайск",
  "Качканар",
  "Кашин",
  "Кашира",
  "Кедровый",
  "Кемерово",
  "Кемь",
  "Керчь",
  "Кизел",
  "Кизилюрт",
  "Кизляр",
  "Кимовск",
  "Кимры",
  "Кингисепп",
  "Кинель",
  "Кинешма",
  "Киреевск",
  "Киренск",
  "Киржач",
  "Кириллов",
  "Кириши",
  "Киров",
  "Киров",
  "Кировград",
  "Кирово",
  "Кировск",
  "Кировск",
  "Кирс",
  "Кирсанов",
  "Киселёвск",
  "Кисловодск",
  "Клин",
  "Клинцы",
  "Княгинино",
  "Ковдор",
  "Ковров",
  "Ковылкино",
  "Когалым",
  "Кодинск",
  "Козельск",
  "Козловка",
  "Козьмодемьянск",
  "Кола",
  "Кологрив",
  "Коломна",
  "Колпашево",
  "Кольчугино",
  "Коммунар",
  "Комсомольск",
  "Комсомольск",
  "Конаково",
  "Кондопога",
  "Кондрово",
  "Константиновск",
  "Копейск",
  "Кораблино",
  "Кореновск",
  "Коркино",
  "Королёв",
  "Короча",
  "Корсаков",
  "Коряжма",
  "Костерёво",
  "Костомукша",
  "Кострома",
  "Котельники",
  "Котельниково",
  "Котельнич",
  "Котлас",
  "Котово",
  "Котовск",
  "Кохма",
  "Красавино",
  "Красноармейск",
  "Красноармейск",
  "Красновишерск",
  "Красногорск",
  "Краснодар",
  "Краснозаводск",
  "Краснознаменск",
  "Краснознаменск",
  "Краснокаменск",
  "Краснокамск",
  "Красноперекопск",
  "Краснослободск",
  "Краснослободск",
  "Краснотурьинск",
  "Красноуральск",
  "Красноуфимск",
  "Красноярск",
  "Красный Кут",
  "Красный Сулин",
  "Красный Холм",
  "Кремёнки",
  "Кропоткин",
  "Крымск",
  "Кстово",
  "Кубинка",
  "Кувандык",
  "Кувшиново",
  "Кудрово",
  "Кудымкар",
  "Кузнецк",
  "Куйбышев",
  "Кукмор",
  "Кулебаки",
  "Кумертау",
  "Кунгур",
  "Купино",
  "Курган",
  "Курганинск",
  "Курильск",
  "Курлово",
  "Куровское",
  "Курск",
  "Куртамыш",
  "Курчалой",
  "Курчатов",
  "Куса",
  "Кушва",
  "Кызыл",
  "Кыштым",
  "Кяхта",
  "Лабинск",
  "Лабытнанги",
  "Лагань",
  "Ладушкин",
  "Лаишево",
  "Лакинск",
  "Лангепас",
  "Лахденпохья",
  "Лебедянь",
  "Лениногорск",
  "Ленинск",
  "Ленинск",
  "Ленск",
  "Лермонтов",
  "Лесной",
  "Лесозаводск",
  "Лесосибирск",
  "Ливны",
  "Ликино",
  "Липецк",
  "Липки",
  "Лиски",
  "Лихославль",
  "Лобня",
  "Лодейное Поле",
  "Лосино",
  "Луга",
  "Луза",
  "Лукоянов",
  "Луховицы",
  "Лысково",
  "Лысьва",
  "Лыткарино",
  "Льгов",
  "Любань",
  "Люберцы",
  "Любим",
  "Людиново",
  "Лянтор",
  "Магадан",
  "Магас",
  "Магнитогорск",
  "Майкоп",
  "Майский",
  "Макаров",
  "Макарьев",
  "Макушино",
  "Малая Вишера",
  "Малгобек",
  "Малмыж",
  "Малоархангельск",
  "Малоярославец",
  "Мамадыш",
  "Мамоново",
  "Мантурово",
  "Мариинск",
  "Мариинский Посад",
  "Маркс",
  "Махачкала",
  "Мглин",
  "Мегион",
  "Медвежьегорск",
  "Медногорск",
  "Медынь",
  "Межгорье",
  "Междуреченск",
  "Мезень",
  "Меленки",
  "Мелеуз",
  "Менделеевск",
  "Мензелинск",
  "Мещовск",
  "Миасс",
  "Микунь",
  "Миллерово",
  "Минеральные Воды",
  "Минусинск",
  "Миньяр",
  "Мирный",
  "Мирный",
  "Михайлов",
  "Михайловка",
  "Михайловск",
  "Михайловск",
  "Мичуринск",
  "Могоча",
  "Можайск",
  "Можга",
  "Моздок",
  "Мончегорск",
  "Морозовск",
  "Моршанск",
  "Мосальск",
  "Москва",
  "Муравленко",
  "Мураши",
  "Мурино",
  "Мурманск",
  "Муром",
  "Мценск",
  "Мыски",
  "Мытищи",
  "Мышкин",
  "Набережные Челны",
  "Навашино",
  "Наволоки",
  "Надым",
  "Назарово",
  "Назрань",
  "Называевск",
  "Нальчик",
  "Нариманов",
  "Наро",
  "Нарткала",
  "Нарьян",
  "Находка",
  "Невель",
  "Невельск",
  "Невинномысск",
  "Невьянск",
  "Нелидово",
  "Неман",
  "Нерехта",
  "Нерчинск",
  "Нерюнгри",
  "Нестеров",
  "Нефтегорск",
  "Нефтекамск",
  "Нефтекумск",
  "Нефтеюганск",
  "Нея",
  "Нижневартовск",
  "Нижнекамск",
  "Нижнеудинск",
  "Нижние Серги",
  "Нижний Ломов",
  "Нижний Новгород",
  "Нижний Тагил",
  "Нижняя Салда",
  "Нижняя Тура",
  "Николаевск",
  "Николаевск",
  "Никольск",
  "Никольск",
  "Никольское",
  "Новая Ладога",
  "Новая Ляля",
  "Новоалександровск",
  "Новоалтайск",
  "Новоаннинский",
  "Нововоронеж",
  "Новодвинск",
  "Новозыбков",
  "Новокубанск",
  "Новокузнецк",
  "Новокуйбышевск",
  "Новомичуринск",
  "Новомосковск",
  "Новопавловск",
  "Новоржев",
  "Новороссийск",
  "Новосибирск",
  "Новосиль",
  "Новосокольники",
  "Новотроицк",
  "Новоузенск",
  "Новоульяновск",
  "Новоуральск",
  "Новохопёрск",
  "Новочебоксарск",
  "Новочеркасск",
  "Новошахтинск",
  "Новый Оскол",
  "Новый Уренгой",
  "Ногинск",
  "Нолинск",
  "Норильск",
  "Ноябрьск",
  "Нурлат",
  "Нытва",
  "Нюрба",
  "Нягань",
  "Нязепетровск",
  "Няндома",
  "Облучье",
  "Обнинск",
  "Обоянь",
  "Обь",
  "Одинцово",
  "Озёрск",
  "Озёрск",
  "Озёры",
  "Октябрьск",
  "Октябрьский",
  "Окуловка",
  "Олёкминск",
  "Оленегорск",
  "Олонец",
  "Омск",
  "Омутнинск",
  "Онега",
  "Опочка",
  "Орёл",
  "Оренбург",
  "Орехово",
  "Орлов",
  "Орск",
  "Оса",
  "Осинники",
  "Осташков",
  "Остров",
  "Островной",
  "Острогожск",
  "Отрадное",
  "Отрадный",
  "Оха",
  "Оханск",
  "Очёр",
  "Павлово",
  "Павловск",
  "Павловский Посад",
  "Палласовка",
  "Партизанск",
  "Певек",
  "Пенза",
  "Первомайск",
  "Первоуральск",
  "Перевоз",
  "Пересвет",
  "Переславль",
  "Пермь",
  "Пестово",
  "Петров Вал",
  "Петровск",
  "Петровск",
  "Петрозаводск",
  "Петропавловск",
  "Петухово",
  "Петушки",
  "Печора",
  "Печоры",
  "Пикалёво",
  "Пионерский",
  "Питкяранта",
  "Плавск",
  "Пласт",
  "Плёс",
  "Поворино",
  "Подольск",
  "Подпорожье",
  "Покачи",
  "Покров",
  "Покровск",
  "Полевской",
  "Полесск",
  "Полысаево",
  "Полярные Зори",
  "Полярный",
  "Поронайск",
  "Порхов",
  "Похвистнево",
  "Почеп",
  "Починок",
  "Пошехонье",
  "Правдинск",
  "Приволжск",
  "Приморск",
  "Приморск",
  "Приморско",
  "Приозерск",
  "Прокопьевск",
  "Пролетарск",
  "Протвино",
  "Прохладный",
  "Псков",
  "Пугачёв",
  "Пудож",
  "Пустошка",
  "Пучеж",
  "Пушкино",
  "Пущино",
  "Пыталово",
  "Пыть",
  "Пятигорск",
  "Радужный",
  "Радужный",
  "Райчихинск",
  "Раменское",
  "Рассказово",
  "Ревда",
  "Реж",
  "Реутов",
  "Ржев",
  "Родники",
  "Рославль",
  "Россошь",
  "Ростов",
  "Ростов",
  "Рошаль",
  "Ртищево",
  "Рубцовск",
  "Рудня",
  "Руза",
  "Рузаевка",
  "Рыбинск",
  "Рыбное",
  "Рыльск",
  "Ряжск",
  "Рязань",
  "Саки",
  "Салават",
  "Салаир",
  "Салехард",
  "Сальск",
  "Самара",
  "Санкт Петербург",
  "Саранск",
  "Сарапул",
  "Саратов",
  "Саров",
  "Сасово",
  "Сатка",
  "Сафоново",
  "Саяногорск",
  "Саянск",
  "Светлогорск",
  "Светлоград",
  "Светлый",
  "Светогорск",
  "Свирск",
  "Свободный",
  "Себеж",
  "Севастополь",
  "Северо",
  "Северобайкальск",
  "Северодвинск",
  "Североморск",
  "Североуральск",
  "Северск",
  "Севск",
  "Сегежа",
  "Сельцо",
  "Семёнов",
  "Семикаракорск",
  "Семилуки",
  "Сенгилей",
  "Серафимович",
  "Сергач",
  "Сергиев Посад",
  "Сердобск",
  "Серов",
  "Серпухов",
  "Сертолово",
  "Сибай",
  "Сим",
  "Симферополь",
  "Сковородино",
  "Скопин",
  "Славгород",
  "Славск",
  "Славянск",
  "Сланцы",
  "Слободской",
  "Слюдянка",
  "Смоленск",
  "Снежинск",
  "Снежногорск",
  "Собинка",
  "Советск",
  "Советск",
  "Советск",
  "Советская Гавань",
  "Советский",
  "Сокол",
  "Солигалич",
  "Соликамск",
  "Солнечногорск",
  "Соль",
  "Сольвычегодск",
  "Сольцы",
  "Сорочинск",
  "Сорск",
  "Сортавала",
  "Сосенский",
  "Сосновка",
  "Сосновоборск",
  "Сосновый Бор",
  "Сосногорск",
  "Сочи",
  "Спас",
  "Спас",
  "Спасск",
  "Спасск",
  "Спасск",
  "Среднеколымск",
  "Среднеуральск",
  "Сретенск",
  "Ставрополь",
  "Старая Купавна",
  "Старая Русса",
  "Старица",
  "Стародуб",
  "Старый Крым",
  "Старый Оскол",
  "Стерлитамак",
  "Стрежевой",
  "Строитель",
  "Струнино",
  "Ступино",
  "Суворов",
  "Судак",
  "Суджа",
  "Судогда",
  "Суздаль",
  "Сунжа",
  "Суоярви",
  "Сураж",
  "Сургут",
  "Суровикино",
  "Сурск",
  "Сусуман",
  "Сухиничи",
  "Сухой Лог",
  "Сызрань",
  "Сыктывкар",
  "Сысерть",
  "Сычёвка",
  "Сясьстрой",
  "Тавда",
  "Таганрог",
  "Тайга",
  "Тайшет",
  "Талдом",
  "Талица",
  "Тамбов",
  "Тара",
  "Тарко",
  "Таруса",
  "Татарск",
  "Таштагол",
  "Тверь",
  "Теберда",
  "Тейково",
  "Темников",
  "Темрюк",
  "Терек",
  "Тетюши",
  "Тимашёвск",
  "Тихвин",
  "Тихорецк",
  "Тобольск",
  "Тогучин",
  "Тольятти",
  "Томари",
  "Томмот",
  "Томск",
  "Топки",
  "Торжок",
  "Торопец",
  "Тосно",
  "Тотьма",
  "Трёхгорный",
  "Троицк",
  "Трубчевск",
  "Туапсе",
  "Туймазы",
  "Тула",
  "Тулун",
  "Туран",
  "Туринск",
  "Тутаев",
  "Тында",
  "Тырныауз",
  "Тюкалинск",
  "Тюмень",
  "Уварово",
  "Углегорск",
  "Углич",
  "Удачный",
  "Удомля",
  "Ужур",
  "Узловая",
  "Улан",
  "Ульяновск",
  "Унеча",
  "Урай",
  "Урень",
  "Уржум",
  "Урус",
  "Урюпинск",
  "Усинск",
  "Усмань",
  "Усолье",
  "Усолье",
  "Уссурийск",
  "Усть",
  "Усть",
  "Усть",
  "Усть",
  "Усть",
  "Устюжна",
  "Уфа",
  "Ухта",
  "Учалы",
  "Уяр",
  "Фатеж",
  "Феодосия",
  "Фокино",
  "Фокино",
  "Фролово",
  "Фрязино",
  "Фурманов",
  "Хабаровск",
  "Хадыженск",
  "Ханты",
  "Харабали",
  "Харовск",
  "Хасавюрт",
  "Хвалынск",
  "Хилок",
  "Химки",
  "Холм",
  "Холмск",
  "Хотьково",
  "Цивильск",
  "Цимлянск",
  "Циолковский",
  "Чадан",
  "Чайковский",
  "Чапаевск",
  "Чаплыгин",
  "Чебаркуль",
  "Чебоксары",
  "Чегем",
  "Чекалин",
  "Челябинск",
  "Чердынь",
  "Черемхово",
  "Черепаново",
  "Череповец",
  "Черкесск",
  "Чёрмоз",
  "Черноголовка",
  "Черногорск",
  "Чернушка",
  "Черняховск",
  "Чехов",
  "Чистополь",
  "Чита",
  "Чкаловск",
  "Чудово",
  "Чулым",
  "Чусовой",
  "Чухлома",
  "Шагонар",
  "Шадринск",
  "Шали",
  "Шарыпово",
  "Шарья",
  "Шатура",
  "Шахты",
  "Шахунья",
  "Шацк",
  "Шебекино",
  "Шелехов",
  "Шенкурск",
  "Шилка",
  "Шимановск",
  "Шиханы",
  "Шлиссельбург",
  "Шумерля",
  "Шумиха",
  "Шуя",
  "Щёкино",
  "Щёлкино",
  "Щёлково",
  "Щигры",
  "Щучье",
  "Электрогорск",
  "Электросталь",
  "Электроугли",
  "Элиста",
  "Энгельс",
  "Эртиль",
  "Югорск",
  "Южа",
  "Южно",
  "Южно",
  "Южноуральск",
  "Юрга",
  "Юрьев",
  "Юрьевец",
  "Юрюзань",
  "Юхнов",
  "Ядрин",
  "Якутск",
  "Ялта",
  "Ялуторовск",
  "Янаул",
  "Яранск",
  "Яровое",
  "Ярославль",
  "Ярцево",
  "Ясногорск",
  "Ясный",
  "Яхрома",
];

export const articles: Array<IArticle> = [
  {
    id: 1,
    image: "article-1",
    subtitle: "Подзаголовок",
    time: new Date(),
    title: "Название статьи",
    content:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus.",
  },
  {
    id: 2,
    image: "article-2",
    subtitle: "Подзаголовок",
    time: new Date(),
    title: "Название статьи",
    content:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus.",
  },
  {
    id: 3,
    image: "article-3",
    subtitle: "Подзаголовок",
    time: new Date(),
    title: "Название статьи",
    content:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio quidem, totam quibusdam ipsam enim numquam, beatae aliquam earum nulla, odit recusandae? Officiis reprehenderit veritatis veniam omnis consequuntur at voluptatem ducimus.",
  },
];

export const navigationTitles: [Array<string>, string][] = [
  [["/notifications", "/notifications/settings"], "Уведомления"],
  [["/articles"], "Журнал"],
  [["/cities"], "Выбор города"],
  [["/specifications"], "Характеристики"],
  [["/filters"], "Фильтры"],
  [["/favourites"], "Избранное"],
];

export const navigationIcons = {
  firstIcon: [
    {
      pages: ["/"],
      icons: [["notifications", "/notifications"]],
    },
    {
      pages: [
        "/notifications",
        "/notifications/settings",
        "/articles",
        "/cities",
        "/chat",
        "/flats",
        "/neighbors",
        "/specifications",
        "/filters",
        "/favourites",
      ],
      icons: [["back", "back"]],
    },
  ],
  secondIcon: [
    {
      pages: ["/cities"],
      icons: null,
    },
    {
      pages: ["/notifications", "/favourites"],
      icons: [["menu", null]],
    },
    {
      pages: ["/articles", "/"],
      icons: [["user", "/profile/1"]],
    },
    {
      pages: ["/flats", "/neighbors"],
      icons: [["filter", "/filters"]],
    },
  ],
};

export const noNavbarsPages = [
  "/sign-in",
  "/sign-up",
  "/questions",
  "/add-apartment",
];

export const profileCircleProgress = "20";

export const profileUsersCards = ["", "", "", "", "", ""];

export const conveniences = [
  "Kондиционер",
  "Балкон",
  "Консьерж",
  "Спортплощадка",
  "Мусоропровод",
];

export const posts = ["", "", ""];

export const navInputPages = ["/chat", "/flats", "/neighbors"];

export const chats: {
  type: "user" | "support";
  message: string;
  name: string;
}[] = [
  {
    type: "support",
    message: "В ваш аккаунт вошли с неизвестного устройсва",
    name: "Поддержка",
  },
  {
    type: "user",
    message: "Урод. Деньги верни",
    name: "Даня",
  },
  {
    type: "user",
    message: "Урод. Деньги верни",
    name: "Даня",
  },
  {
    type: "user",
    message: "Урод. Деньги верни",
    name: "Даня",
  },
  {
    type: "user",
    message: "Урод. Деньги верни",
    name: "Даня",
  },
];

export const flats: Array<IFlat> = [
  {
    id: 1,
    user: users[0],
    price: 15000,
  },
  {
    id: 2,
    user: users[1],
    price: 20000,
  },
  {
    id: 3,
    user: users[2],
    price: 21000,
  },
];

export const maxFlatPrice = flats
  .sort((a, b) => a.price - b.price)
  .reverse()[0].price;
export const maxUsersAge = users.sort((a, b) => a.age - b.age).reverse()[0].age;

export const animals: { animal: TAnimals; icon: IconType; label: string }[] = [
  {
    animal: "cat",
    icon: FaCat,
    label: "Кошка",
  },
  {
    animal: "dog",
    icon: FaDog,
    label: "Собака",
  },
  {
    animal: "lizard",
    icon: FaHandLizard,
    label: "Ящерица",
  },
  {
    animal: "rabbit",
    icon: GiRabbit,
    label: "Кролик",
  },
];

export const habits: {
  habit: THabits;
  label: string;
}[] = [
  { habit: "smoking", label: "Курение" },
  { habit: "sport", label: "Занятие спортом" },
  { habit: "night owl", label: "Полуночник" },
  { habit: "early bird", label: "Ранний подъем" },
];

export const houseType = [
  "Новостройка-жк",
  "Советский фонд",
  "Сталинки",
  "Старый фонд",
  "Частный дом",
];
export const repair = ["Бабушкин", "Современный", "Дизайнерский"];
export const soundIsolation = ["Идеальная", "Приемлемо", "Картон"];
export const comfort = [
  "Лифт",
  "Балкон",
  "Парковочное место",
  "Охрана или консьерж",
  "Турники во дворе",
  "Кондей",
  "Мусоропровод",
  "Вайфай",
  "Транспорт в пешей доступности",
];
export const appliances = [
  "Стиралка",
  "Сушилка/полотенцесушитель",
  "Посудомойка",
  "Фен",
  "Телек",
  "Отдельный шкаф",
  "Отдельный стол",
];
